on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - "resources/**"
jobs:
  build:
    runs-on: ubuntu-latest
    name: "test"
    steps:
      - id: "checkout"
        uses: actions/checkout@v2
        name: "Checkout source code"
      - id: "test"
        uses: actions/tools.deps-builder@v1.0.1
        name: "Run tests"
