on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - "resources/**"
      - ".github/workflows/test.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    name: "test"
    steps:
      - id: "checkout"
        uses: actions/checkout@v2
        name: "Checkout source code"
      - id: "test"
        uses: vouch-opensource/tools.deps-build@1.0.1
        name: "Run tests"
